Repository instadeepai/jumanji, pull requests merged in 2022-11, with the labels that each got.

#39 feat: explicit version number and testing
  docs/guides/registration.md
  jumanji/registration.py
  jumanji/registration_test.py
Labels: enhancement

#49 docs: update the contributing document with jumanji api 0.1.x
  CONTRIBUTING.md
Labels: documentation

#52 fix: import cvrp for environment registration
  jumanji/environments/__init__.py
Labels: bug

#59 fix: import protocol from typing extensions to ensure Python 3.7 compatibility
  jumanji/env.py
Labels: bug
