Repository instadeepai/jumanji, pull requests merged in 2022-09, with the labels that each got.

#16 Fix rendering of table in Examples section.
  README.md
Labels: bug, documentation

#18 bug: make pull requests trigger workflow
  .github/workflows/tests_linters.yml
Labels: bug

#21 fix: brax wrapper docstring
  jumanji/wrappers.py
Labels: documentation
