Repository instadeepai/jumanji, pull requests merged in 2023-05, with the labels that each got.

#126 fix(generator_maze): correct definition of width and height
  jumanji/environments/commons/maze_utils/maze_generation.py
  jumanji/environments/routing/cleaner/generator.py
  jumanji/environments/routing/cleaner/generator_test.py
Labels: bug, documentation

#123 fix: make autoreset wrapper return 2 on reset
  jumanji/wrappers.py
  jumanji/wrappers_test.py
Labels: enhancement, good first issue

#122 feat(maze): update generator to return state
  jumanji/environments/routing/maze/env.py
  jumanji/environments/routing/maze/generator.py
Labels: enhancement

#137 feat(tsp): generator
  jumanji/environments/routing/tsp/conftest.py
  jumanji/environments/routing/tsp/env.py
  jumanji/environments/routing/tsp/generator.py
  jumanji/environments/routing/tsp/generator_test.py
Labels: enhancement

#145 fix(training): connector num_agents in networks
  jumanji/training/evaluator.py
  jumanji/training/networks/connector/actor_critic.py
Labels: bug

#138 feat(cvrp): generator
  jumanji/environments/routing/cvrp/conftest.py
  jumanji/environments/routing/cvrp/env.py
  jumanji/environments/routing/cvrp/generator.py
  jumanji/environments/routing/cvrp/generator_test.py
Labels: enhancement

#139 feat(knapsack): generator
  jumanji/environments/packing/knapsack/conftest.py
  jumanji/environments/packing/knapsack/env.py
  jumanji/environments/packing/knapsack/generator.py
  jumanji/environments/packing/knapsack/generator_test.py
Labels: enhancement

#142 fix(parametric_action_distribution): sum kl divergence over event_ndims in parametric action distribution
  jumanji/training/networks/parametric_distribution.py
Labels: bug, enhancement
