Repository instadeepai/jumanji, pull requests merged in 2023-06, with the labels that each got.

#150 fix: put upper bounds on versions of jax and jaxlib
  requirements/requirements.txt
Labels: bug

#140 feat(robot_warehouse): full environment
  README.md
  docs/api/environments/rware.md
  docs/env_anim/rware.gif
  docs/env_img/rware.png
  docs/environments/robot_warehouse.md
  jumanji/__init__.py
  jumanji/environments/__init__.py
  jumanji/environments/routing/robot_warehouse/__init__.py
  jumanji/environments/routing/robot_warehouse/conftest.py
  jumanji/environments/routing/robot_warehouse/constants.py
  jumanji/environments/routing/robot_warehouse/env.py
  jumanji/environments/routing/robot_warehouse/env_test.py
  jumanji/environments/routing/robot_warehouse/generator.py
  jumanji/environments/routing/robot_warehouse/generator_test.py
  jumanji/environments/routing/robot_warehouse/types.py
  jumanji/environments/routing/robot_warehouse/utils.py
  jumanji/environments/routing/robot_warehouse/utils_agent.py
  jumanji/environments/routing/robot_warehouse/utils_shelf.py
  jumanji/environments/routing/robot_warehouse/utils_spawn.py
  jumanji/environments/routing/robot_warehouse/utils_test.py
  jumanji/environments/routing/robot_warehouse/viewer.py
  jumanji/environments/routing/robot_warehouse/viewer_test.py
  jumanji/training/configs/config.yaml
  jumanji/training/configs/env/rware.yaml
  jumanji/training/networks/__init__.py
  jumanji/training/networks/robot_warehouse/__init__.py
  jumanji/training/networks/robot_warehouse/actor_critic.py
  jumanji/training/networks/robot_warehouse/random.py
  jumanji/training/setup_train.py
Labels: enhancement

#125 feat(sudoku): implement environment
  .pre-commit-config.yaml
  README.md
  docs/api/environments/sudoku.md
  docs/env_anim/sudoku.gif
  docs/env_img/sudoku.png
  docs/environments/sudoku.md
  examples/load_checkpoints.ipynb
  examples/training.ipynb
  jumanji/__init__.py
  jumanji/environments/__init__.py
  jumanji/environments/logic/sudoku/__init__.py
  jumanji/environments/logic/sudoku/conftest.py
  jumanji/environments/logic/sudoku/constants.py
  jumanji/environments/logic/sudoku/data/10000_mixed_puzzles.npy
  jumanji/environments/logic/sudoku/data/1000_very_easy_puzzles.npy
  jumanji/environments/logic/sudoku/data/__init__.py
  jumanji/environments/logic/sudoku/env.py
  jumanji/environments/logic/sudoku/env_test.py
  jumanji/environments/logic/sudoku/generator.py
  jumanji/environments/logic/sudoku/reward.py
  jumanji/environments/logic/sudoku/types.py
  jumanji/environments/logic/sudoku/utils.py
  jumanji/environments/logic/sudoku/utils_test.py
  jumanji/environments/logic/sudoku/viewer.py
  jumanji/training/configs/config.yaml
  jumanji/training/configs/env/sudoku.yaml
  jumanji/training/networks/__init__.py
  jumanji/training/networks/sudoku/__init__.py
  jumanji/training/networks/sudoku/actor_critic.py
  jumanji/training/networks/sudoku/random.py
  jumanji/training/setup_train.py
Labels: enhancement

#154 docs: image fixes
  docs/env_anim/robot_warehouse.gif
  docs/env_img/bin_pack.png
  docs/env_img/cleaner.png
  docs/env_img/robot_warehouse.png
  docs/environments/job_shop.md
  docs/img/job_shop_annotated.gif
  jumanji/environments/routing/connector/env.py
Labels: documentation

#156 feat: paper configs
  .gitignore
  README.md
  docs/environments/bin_pack.md
  docs/environments/connector.md
  docs/environments/mmst.md
  docs/environments/tetris.md
  jumanji/__init__.py
  jumanji/environments/packing/bin_pack/env.py
  jumanji/environments/packing/knapsack/env.py
  jumanji/environments/packing/tetris/env.py
  jumanji/environments/routing/connector/env.py
  jumanji/environments/routing/mmst/env.py
  jumanji/environments/routing/mmst/types.py
  jumanji/environments/routing/mmst/utils.py
  jumanji/environments/routing/mmst/viewer_test.py
  jumanji/training/configs/config.yaml
  jumanji/training/configs/env/bin_pack.yaml
  jumanji/training/configs/env/connector.yaml
  jumanji/training/configs/env/cvrp.yaml
  jumanji/training/configs/env/game_2048.yaml
  jumanji/training/configs/env/knapsack.yaml
  jumanji/training/configs/env/mmst.yaml
  jumanji/training/configs/env/multi_cvrp.yaml
  jumanji/training/configs/env/robot_warehouse.yaml
  jumanji/training/configs/env/rubiks_cube.yaml
  jumanji/training/configs/env/snake.yaml
  jumanji/training/configs/env/tetris.yaml
  jumanji/training/configs/env/tsp.yaml
  jumanji/training/networks/mmst/actor_critic.py
  jumanji/training/networks/tetris/actor_critic.py
  jumanji/training/setup_train.py
Labels: enhancement

#158 docs: update online doc with new environments
  README.md
  docs/api/env.md
  docs/env_anim/robot_warehouse.gif
  docs/env_anim/tetris.gif
  docs/env_img/robot_warehouse.png
  docs/env_img/tetris.png
  mkdocs.yml
Labels: documentation

#164 feat(training): multi-worker training
  jumanji/training/evaluator.py
  jumanji/training/loggers.py
  jumanji/training/setup_train.py
  jumanji/training/train.py
Labels: enhancement

#167 ci: increment version
  README.md
  jumanji/version.py
  setup.py
Labels: ci

#174 ci: update to latest jax and chex
  jumanji/testing/pytrees.py
  jumanji/testing/pytrees_test.py
  jumanji/wrappers.py
  requirements/requirements.txt
Labels: ci

#175 build: remove jaxlib
  requirements/requirements.txt
Labels: ci

#176 docs: update readme citation
  README.md
Labels: documentation

#177 build: bump version to 0.3.1
  jumanji/version.py
Labels: ci

#181 fix: latest chex and jax
  jumanji/training/loggers.py
  jumanji/training/utils.py
Labels: bug
